[package]
name = "svelte-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
cliclack = "0.3.5"
log = "0.4.22"
console = "0.15.8"
serde_json = "1.0.132"
clap = { version = "4.5.20", features = ["derive"] }
