name: Rust Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-pc-windows-msvc
          - i686-pc-windows-msvc

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        target: ${{ matrix.target }}

    - name: Build for target
      run: cargo build --target ${{ matrix.target }} --release --verbose

    - name: Copy binary to bin
      run: |
        mkdir -p bin/${{ matrix.target }}
        cp target/${{ matrix.target }}/release/* bin/${{ matrix.target }}/
